---
name: Checks

on: 
  pull_request:
    branches:
      - main


jobs: 
  test-lint:
    name: Lint and Test
    runs-on:
      ubuntu-20.04
      steps:
        - name: Login to Docker
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Lint
          run: docker-compose run --rm app sh -c "flake8"
        - name: Test
          run: docker-compose run --rm app sh -c "python manage.py test"
